Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System.Dynamic;
using LIONFIT.Data;
using LIONFIT.Models;
namespace LIONFIT.Controllers
{

    public class CarritoController : Controller
    {
        private readonly ILogger<CarritoController> _logger;
        private readonly ApplicationDbContext _dbcontext;
        private readonly UserManager<IdentityUser> _userManager;

        public CarritoController(ILogger<CarritoController> logger, ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _logger = logger;
            _dbcontext = context;
            _userManager = userManager;

        }

        public IActionResult Index()
        {
            var userIDSession = _userManager.GetUserName(User);

            //SELECT * FROM Proforma p,Producto pr WHERE p.productId=pr.Id And p.UserId=? And p.status='PENDIENTE' 
            var items = from o in _dbcontext.Databoleta select o;
            items = items.Include(p => p.Producto).
                    Where(w => w.UserID.Equals(userIDSession));
            var itemsCarrito = items.ToList();
            //Fila1 1234, Shampo; Precio, Cantidad
            //Fila2 12345, Shampo3; Precio, Cantidad
            var total = itemsCarrito.Sum(c => c.Cantidad * c.Precio);

            //MEMORIA
            dynamic model = new ExpandoObject();
            model.montoTotal = total;
            model.elementosCarrito = itemsCarrito;

            //Carrito carrito = new Carrito();
            //carrito.total = total;
            //carrito.itemsCarrito = itemsCarrito;

            //return View(carrito);
            return View(model);
        }

        public IActionResult Delete(int id)
        {
            // Busca el producto por su Id
            var product = _dbcontext.Databoleta.FirstOrDefault(p => p.Id == id);

            if (product == null)
            {
                return NotFound(); // Si el producto no existe, retorna un error 404
            }

            _dbcontext.Databoleta.Remove(product); // Elimina el producto del contexto de datos
            _dbcontext.SaveChanges(); // Guarda los cambios en la base de datos

            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Boleta = await _dbcontext.Databoleta.FindAsync(id);
            if (Boleta == null)
            {
                return NotFound();
            }
            return View(Boleta);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Cantidad,Precio,UserID")] Boleta boleta)
        {
            if (id != boleta.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _dbcontext.Update(boleta);
                    await _dbcontext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_dbcontext.Databoleta.Any(e => e.Id == id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(boleta);
        }

        [HttpPost]
        public  async Task<IActionResult> Delete(int? id){
                
                if(id == null){
                    return NotFound();
                }
                var boleta= await _dbcontext.Databoleta.FindAsync(id);
                _dbcontext.Databoleta.Remove(boleta);
                await _dbcontext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/FoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LIONFIT.Models;
using LIONFIT.Integration.Food;

namespace LIONFIT.Controllers
{
    [Route("[controller]")]
    public class FoodController : Controller
    {
        private readonly ILogger<FoodController> _logger;
        private readonly FoodIntegration _food ;

        public FoodController(ILogger<FoodController> logger, FoodIntegration food)
    {
        _logger = logger;
        _food = food;
    }

    [HttpGet("")]
public async Task<IActionResult> Index(string search)
{
    try
    {
        var alimentos = await _food.GetAlimentosAsync();
        var dataComidas = new List<Alimento>();

        if (alimentos != null && alimentos.Count > 0)
        {
            if (string.IsNullOrEmpty(search))
            {
                dataComidas = alimentos;
            }
            else
            {
                dataComidas = alimentos.Where(p => p.Title.ToLower().Contains(search.ToLower())).ToList();
            }
        }

        ViewData["Search"] = search;
        return View("~/Views/Food/Index.cshtml", dataComidas);
    }
    catch (Exception ex)
    {
        // Manejar la excepción adecuadamente, por ejemplo, mostrar un mensaje de error en la vista
        ViewBag.ErrorMessage = $"Error al obtener los datos de la API: {ex.Message}";
        return View("Error");
    }
}

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [HttpGet("error")]
    public IActionResult Error()
    {
        return View("Error!");
    }

    }
}

Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity;

using LIONFIT.Data;
using LIONFIT.Models;
using Microsoft.EntityFrameworkCore;

namespace LIONFIT.Controllers
{
    [Route("[controller]")]
    public class PedidoController : Controller
    {
        private readonly ILogger<PedidoController> _logger;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _context;

        public PedidoController(ILogger<PedidoController> logger, UserManager<IdentityUser> userManager, ApplicationDbContext context)
        {
            _logger = logger;
             _userManager = userManager;
            _context = context;
        }

        [HttpGet]
[Route("Index")]
         public  async Task<IActionResult>Index()
        {
             var pedidos = from o in _context.DataPedido select o;
             pedidos = pedidos.Where(s => s.Status.Contains("PENDIENTE"));
            
            return View(await pedidos.ToListAsync());
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LIONFIT.Data;
using LIONFIT.Models;
using LIONFIT.Service;

namespace LIONFIT.Controllers
{
    public class ProductoController : Controller
    {

        private readonly ProductoService _productoService;


        public ProductoController(ProductoService productoService)
        {

            _productoService = productoService;
        }

        // GET: Producto
       [HttpGet]
        [Route("/Producto/")]
        public async Task<IActionResult> Index()
        {

            var productos = await _productoService.GetAll();
            return productos != null ?
                View(productos) :
                  Problem("Entity set 'ApplicationDbContext.Dataproducto'  is null.");

        }

        // GET: Producto/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = _productoService.FirstOrDefault(id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // GET: Producto/Create
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NomProducto,Precio,DesProducto,Imagen,Status")] Producto producto)
        {
            if (ModelState.IsValid)
            {

                await _productoService.Create_Update(producto);
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        // GET: Producto/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var producto = await _productoService.Get(id);
            if (producto == null)
            {
                return NotFound();
            }
            return View(producto);
        }

        // POST: Producto/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomProducto,Precio,DesProducto,Imagen,Status")] Producto producto)
        {
            if (id != producto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _productoService.Create_Update(producto);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_productoService.ProductoExists(producto.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        // GET: Producto/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var producto = await _productoService.Get(id);
            if (producto == null)
            {
                return NotFound();
            }
            return View(producto);
        }

        // POST: Producto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _productoService.Delete(id);
            return RedirectToAction(nameof(Index));
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LIONFIT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/footersite.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/details.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/carrito.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/nosotros.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/pago.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/pedidos.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/maps.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/edit.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/producto.css" asp-append-version="true" />


    <link rel="stylesheet" href="~/LIONFIT.styles.css" asp-append-version="true" />

    <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap" rel="stylesheet">


</head>


<body>
    <div class="mi_contenedor">

        <div class="mi_container">
            <div class="pantalla-carga">
                <div class="pantalla-carga">
                    <img class="imagen_b" src="https://drive.google.com/uc?id=1pR1ZadN2j-3FoyruYQ8sNyjfGKweLmJW"
                        alt="Cargando...">
                    <div class="circulo-carga"></div>
                </div>
            </div>


            <header>
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow mb-3"
                    style="background-color: #E14545;">
                    <div class="container-fluid">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                            <img src="https://drive.google.com/uc?id=1pR1ZadN2j-3FoyruYQ8sNyjfGKweLmJW" alt="LIONFIT"
                                style="max-height: 60px;width: 50px;">
                        </a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1  ">
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Home"
                                        asp-action="Index">Inicio</a>
                                </li>
                               
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Home"
                                        asp-action="Nosotros">Nosotros</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Food"
                                        asp-action="Index">API</a>
                                </li>
                                <partial name="_MenuAdminPartial" />
                            </ul>
                            <partial name="_LoginPartial" />
                        </div>
                    </div>
                </nav>
            </header>


            <div class="back">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>

            <footer class="footer">
                <div class="containerfooter">
                    <div class="row">
                        <div class="footer-col">
                            <h4>LionFit</h4>
                            <ul>
                                <li><a asp-controller="Home" asp-action="Index">Nuestro Servicio</a></li>
                            </ul>
                        </div>

                
                        <div class="footer-col">
                            <h4>Consultas</h4>
                            <ul>
                                <li><a asp-controller="Carrito" asp-action="Index">Mi Carrito</a></li>
                                <li>
                                    <p>Medios de Pago:</p>
                                </li>
                                <li>
                                    <p style="font-size: 40px;"> <i class="fab fa-cc-visa"></i> - <i
                                            class="fab fa-cc-mastercard"></i></p>
                                </li>
                            </ul>
                        </div>
                        <div class="footer-col">
                            <h4>Redes Sociales</h4>
                            <div class="social-links">
                                <a class="fb" href="https://www.facebook.com/people/LionFit-Store/100092302690244/"><i
                                        class="fab fa-facebook-f"></i></a>
                                <a class="tw" href="https://twitter.com/LionFit2003"><i class="fab fa-twitter"></i></a>
                                <a class="ig" href="#"><i class="fab fa-instagram"></i></a>
                                <a class="gh" href="https://github.com/LIONFIT"><i class="fab fa-github"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        </div>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://kit.fontawesome.com/2c36e9b7b1.js" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_MenuAdminPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Collections.Generic;

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


@if (SignInManager.IsSignedIn(User))
{
    IdentityUser myidentity = await Task.Run(() => UserManager.GetUserAsync(User));
    var roles = await Task.Run(() => UserManager.GetRolesAsync(myidentity));

    @if (roles.Contains("admin"))
    {
        <li class="nav-item">
            <a class="nav-link text-white bi bi-cart" asp-area="" asp-controller="Pedido" asp-action="Index">Pedidos</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white bi bi-cart" asp-area="" asp-controller="Producto" asp-action="Index">Productos</a>
        </li>

    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-white" asp-area="" asp-controller="CatalogoProductos" asp-action="Index">Productos</a>
        </li>
    }

}
else
{
    <li class="nav-item">
        <a class="nav-link text-white" asp-area="" asp-controller="CatalogoProductos" asp-action="Index">Productos</a>
    </li>
}