Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System.Dynamic;
using LIONFIT.Data;
using LIONFIT.Models;
namespace LIONFIT.Controllers
{

    public class CarritoController : Controller
    {
        private readonly ILogger<CarritoController> _logger;
        private readonly ApplicationDbContext _dbcontext;
        private readonly UserManager<IdentityUser> _userManager;

        public CarritoController(ILogger<CarritoController> logger, ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _logger = logger;
            _dbcontext = context;
            _userManager = userManager;

        }

        public IActionResult Index()
        {
            var userIDSession = _userManager.GetUserName(User);

            //SELECT * FROM Proforma p,Producto pr WHERE p.productId=pr.Id And p.UserId=? And p.status='PENDIENTE' 
            var items = from o in _dbcontext.Databoleta select o;
            items = items.Include(p => p.Producto).
                    Where(w => w.UserID.Equals(userIDSession));
            var itemsCarrito = items.ToList();
            //Fila1 1234, Shampo; Precio, Cantidad
            //Fila2 12345, Shampo3; Precio, Cantidad
            var total = itemsCarrito.Sum(c => c.Cantidad * c.Precio);

            //MEMORIA
            dynamic model = new ExpandoObject();
            model.montoTotal = total;
            model.elementosCarrito = itemsCarrito;

            //Carrito carrito = new Carrito();
            //carrito.total = total;
            //carrito.itemsCarrito = itemsCarrito;

            //return View(carrito);
            return View(model);
        }

        public IActionResult Delete(int id)
        {
            // Busca el producto por su Id
            var product = _dbcontext.Databoleta.FirstOrDefault(p => p.Id == id);

            if (product == null)
            {
                return NotFound(); // Si el producto no existe, retorna un error 404
            }

            _dbcontext.Databoleta.Remove(product); // Elimina el producto del contexto de datos
            _dbcontext.SaveChanges(); // Guarda los cambios en la base de datos

            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Boleta = await _dbcontext.Databoleta.FindAsync(id);
            if (Boleta == null)
            {
                return NotFound();
            }
            return View(Boleta);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Cantidad,Precio,UserID")] Boleta boleta)
        {
            if (id != boleta.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _dbcontext.Update(boleta);
                    await _dbcontext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_dbcontext.Databoleta.Any(e => e.Id == id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(boleta);
        }

        [HttpPost]
        public  async Task<IActionResult> Delete(int? id){
                
                if(id == null){
                    return NotFound();
                }
                var boleta= await _dbcontext.Databoleta.FindAsync(id);
                _dbcontext.Databoleta.Remove(boleta);
                await _dbcontext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/PagoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity;
using LIONFIT.Data;
using LIONFIT.Models;
using Microsoft.EntityFrameworkCore;

namespace LIONFIT.Controllers

{
    [Route("[controller]")]
    public class PagoController : Controller
    {
        private readonly ILogger<PagoController> _logger;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _context;

        public PagoController(ILogger<PagoController> logger, UserManager<IdentityUser> userManager, ApplicationDbContext context)
        {
            _logger = logger;
             _userManager = userManager;
            _context = context;
        }

      
        [Route("Create")]
       public IActionResult Create(Decimal monto)
        {

            Pago pago = new Pago();
            pago.UserId = _userManager.GetUserName(User);
            pago.MontoTotal = monto;
            return View(pago);
        }

         [HttpPost]
         [Route("Create/Pagar")]
        public IActionResult Pagar(Pago pago)
        {
            pago.PaymenDate = DateTime.UtcNow;
            _context.Add(pago);
            
            var itemsBoleta = from o in _context.Databoleta select o;
            itemsBoleta = itemsBoleta.
                Include(p => p.Producto).
                Where(s => s.UserID.Equals(pago.UserId) && s.Status.Equals("PENDIENTE"));

            Pedido pedido = new Pedido();
            pedido.UserID = pago.UserId;
            pedido.Total = pago.MontoTotal;
            pedido.pago = pago;
            pedido.Status = "PENDIENTE";
            _context.Add(pedido);

            List<DetallePedido> itemsPedido = new List<DetallePedido>();
            foreach(var item in itemsBoleta.ToList()){
                DetallePedido detallePedido = new DetallePedido();
                detallePedido.pedido=pedido;
                detallePedido.Precio = item.Precio;
                detallePedido.Producto = item.Producto;
                detallePedido.Cantidad = item.Cantidad;
                itemsPedido.Add(detallePedido);
            }


            _context.AddRange(itemsPedido);

            foreach (Boleta p in itemsBoleta.ToList())
            {
                p.Status="PROCESADO";
            }

            _context.UpdateRange(itemsBoleta);

            _context.SaveChanges();

            ViewData["Message"] = "El pago se ha registrado y su pedido nro "+ pedido.ID +" esta en camino";
            return View("Create");
        }

    
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Carrito/Edit.cshtml
@model LIONFIT.Models.Boleta

@{
    ViewData["Title"] = "Edit";
}
<div class="cabina">

<div class="titu">
<h1>EDITAR PRODUCTO</h1>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Carrito" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="UserID" />
            <input type="hidden" asp-for="Precio" />
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br>
<div>
    <a class="indis"asp-action="Index">Regresar</a>
</div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Carrito/Index.cshtml
@model dynamic;
@using System.Collections.Generic;

@{
    ViewData["Title"] = "Carrito";
    IEnumerable<LIONFIT.Models.Boleta> listItemsCarrito = new List<Boleta>();
    if (Model != null && Model.elementosCarrito != null)
    {
        listItemsCarrito = Model.elementosCarrito;
    }
    Decimal montoTotal = @Model.montoTotal;
}
<div class="container bo">
    <div class="titulo-carrito">
        <h1>@ViewData["Title"]</h1>
    </div>
    <div class="carrito_compras">
        <div class="button-container">
            <div class="item1">

                 <a class="minimal-button" asp-controller="Pago" asp-action="Create" asp-route-monto="@montoTotal">  
                    <span>Pagar</span>
                    <span class="button-icon"></span>
                </a>
              

            </div>
            <div class="item2">
                <p class="producto edid">Total S/. @montoTotal</p>
            </div>
        </div>
        <br>
        <br>

        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => listItemsCarrito.FirstOrDefault().Producto.NomProducto)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => listItemsCarrito.FirstOrDefault().Cantidad)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => listItemsCarrito.FirstOrDefault().Precio)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (Boleta item in Model.elementosCarrito)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Producto.NomProducto)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cantidad)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Precio)
                        </td>
                        <td>
                            <div class="B"></div>
                            <div class="b">
                            <a asp-action="Edit" asp-route-id="@item.Id" class="edit-link">
                                <ion-icon size="small" name="create-outline"></ion-icon>
                            </a>
                            </div>
                            <div class="b">
                            <a asp-action="Delete" asp-route-id="@item.Id">
                                <ion-icon size="small" name="trash-outline">

                                </ion-icon> </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>